Feature/update deprecated function
humanmade/wp-permastructure pull request #2
Opened 2017-05-22 13:35 UTC by mmaton

2017-05-23 01:18 UTC, rmccue commented
Thanks @mmaton!

@roborourke is there a reason for maintaining our own fork here? If so, this PR's for you. :)

2017-05-23 08:54 UTC, mmaton commented
@roborourke @rmccue I believe this was used for work with Immediate Media - we are currently discussing cloning this repo into our private GitHub and maintaining it there.

2017-05-24 14:18 UTC, roborourke requested changes

2017-05-24 14:18 UTC, roborourke commented on wp-permastructure.php
> +		// Yoast Sitemap plug-in doesn't pass a WP_Post object causing a fatal, so we'll check for it and return.
@mmaton what does Yoast sitemap pass here exactly? If it's a post ID then the first line of this method could be:

```php
$post = get_post( $post );
```

then it won't matter what the type is, object, int or null for global post.

2017-05-24 14:19 UTC, roborourke commented
@mmaton thanks for this - I'm not sure bailing from the function is the right answer though. You'd get incorrect links in the sitemap.

2017-05-25 09:48 UTC, mmaton commented on wp-permastructure.php
> +		// Yoast Sitemap plug-in doesn't pass a WP_Post object causing a fatal, so we'll check for it and return.
@roborourke - I was including changes from the perceived original plugin author: https://github.com/interconnectit/wp-permastructure

2017-05-25 10:04 UTC, Rayrn commented
@roborourke First of, I'm assuming that you're talking about lines 246-248. Just to note that this is a change introduced by the original plugin author rather than by immediate.

I agree that this solution is sub-optimal and leaves us open to bad links, however the comment tagging Yoast as the cause (and my brief research) leads me to believe that this issue is unlikely to affect us, and as such, addressing it is not worth the risk of additional changes from the root project.

2017-05-25 10:15 UTC, mmaton commented
I can confirm that there are no anomalies in our site-wide interface tests, nor are there any issues with sitemap generation. It appears that parse_permalinks is indeed called with a WP_Post object in sitemap generation.

```
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:n="http://www.google.com/schemas/sitemap-news/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
<url>
<loc>
http://[redacted]/uncategorized/test-article-22/
</loc>
<lastmod>2017-05-24T10:35:35+00:00</lastmod>
<changefreq>monthly</changefreq>
<priority>0.7</priority>
</url>
<url>
<loc>
http://[redacted]/uncategorized/test-article-20/
</loc>
<lastmod>2017-05-24T10:34:53+00:00</lastmod>
<changefreq>monthly</changefreq>
<priority>0.7</priority>
</url>
<url>
<loc>
http://[redacted]/uncategorized/test-article-15/
</loc>
<lastmod>2017-05-24T10:33:34+00:00</lastmod>
<changefreq>monthly</changefreq>
<priority>0.7</priority>
</url>
<url>
<loc>
http://[redacted]/uncategorized/test-article-14/
</loc>
<lastmod>2017-05-24T10:34:11+00:00</lastmod>
<changefreq>monthly</changefreq>
<priority>0.7</priority>
</url>
<url>
<loc>
http://[redacted]/uncategorized/test-article-9/
</loc>
<lastmod>2017-05-24T10:33:25+00:00</lastmod>
<changefreq>monthly</changefreq>
<priority>0.7</priority>
</url>
</urlset>
```

2017-05-26 07:30 UTC, roborourke commented
@mmaton @Rayrn alright thanks both - I did indeed originally write this when I worked at interconnect but I no longer have access to the main repo. I'll merge this in to get up to date with the upstream then make another update to use `get_post()` instead.

2017-05-26 07:31 UTC, roborourke approved these changes

2017-05-26 07:31 UTC, merged

2017-05-26 08:17 UTC, roborourke commented
@mmaton @Rayrn I've made a PR from here against the interconnect repo now so you may be able to switch the submodule to point there once updated. If you need to make further changes it may work better for you in future to fork the upstream repo.